---
title: "RF_imp"
output: html_document
---

mofa on tonsil test


```{r}
library(MOFA2)

# read in view data
df1 = read.csv('./feature_meta.csv')
features_names = c('HOECHST1', 'CD38', 'CD19', 'CD31',
        'Vimentin', 'CD22', 'Ki67', 'CD8', 'CD90', 'CD123', 'CD15', 'CD3',
        'CD152', 'CD21', 'cytokeratin', 'CD2', 'CD66', 'collagen.IV', 'CD81',
        'HLA.DR', 'CD57', 'CD4', 'CD7', 'CD278', 'podoplanin', 'CD45RA', 'CD34',
        'CD54', 'CD9', 'IGM', 'CD117', 'CD56', 'CD279', 'CD45', 'CD49f', 'CD5',
        'CD16', 'CD63', 'CD11b', 'CD1c', 'CD40', 'CD274', 'CD27', 'CD104',
        'CD273', 'FAPalpha', 'Ecadherin')
df12 = df1[,features_names]

library(reshape2)
df12_s=as.data.frame(scale(df12))
df12_s$id = c(1:nrow(df12_s))
df12_m = melt(df12_s, id = 'id')
df12_m$view = 'view_0'
```


```{r}
df2 = read.csv('./cell_nbhd_res0.5_k20.csv')
df2$X <- NULL

###
df2_s=as.data.frame(scale(df2))
df2_s$id = c(1:nrow(df2_s))
df2_m = melt(df2_s, id = 'id')
df2_m$view = 'view_1'
```


```{r}
mofa_input = rbind(df12_m, df2_m)
colnames(mofa_input) = c('sample', 'feature', 'value', 'view')

### all just default option
MOFAobject <- create_mofa(mofa_input)
data_opts <- get_default_data_options(MOFAobject)
model_opts <- get_default_model_options(MOFAobject)
head(model_opts)
train_opts <- get_default_training_options(MOFAobject)

MOFAobject <- prepare_mofa(
  object = MOFAobject,
  data_options = data_opts,
  model_options = model_opts,
  training_options = train_opts
)

outfile = file.path(getwd(),"model.hdf5")
MOFAobject.trained <- run_mofa(MOFAobject, outfile)
```

```{r}
mofa_res = MOFAobject.trained@expectations$Z$single_group
write.csv(mofa_res, './mofa_fc23.csv', row.names = FALSE)
```




