---
title: "retrain_plot"
output: html_document
---

```{r}
df1 = read.csv('../data/xton_previousCellSNAP.csv')
df1$Model = 'CellLENS default (w training)'
df2 = read.csv('../data/xton_ResReloss.csv')
df2$Model = 'CellLENS ResNet50 (w trained)'
df3 = read.csv('../data/xton_ViTReloss.csv')
df3$Model = 'CellLENS ViT (w trained)'

dfall = rbind(df1, df2, df3)
dfall$Model = factor(dfall$Model, levels = c('CellLENS default (w training)',
                                             'CellLENS ResNet50 (w trained)',
                                             'CellLENS ViT (w trained)'))
```

```{r}
library(dplyr)

temp = subset(dfall, dfall$Loss_type == 'L1')
# Data
data <- temp %>% select(Loss, Model) 
# Calculates mean, sd, se and IC
my_sum <- data %>%
  group_by(Model) %>%
  dplyr::summarise( 
    n=n(),
    mean=mean(Loss),
    sd=sd(Loss)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
library(ggplot2)
# Standard deviation
p = ggplot(my_sum) +
  geom_bar( aes(x=Model, y=mean, fill=Model), stat="identity", alpha=0.7, width = 0.4) +
  geom_errorbar( aes(x=Model, ymin=mean-sd, ymax=mean+sd), width=0.08, colour="black", alpha=0.9, size=0.2) +
  geom_point(data = temp, aes(x = Model, y = Loss), color = 'black', 
              width = 0, alpha = 0.6, size = 0.75) +
  ggtitle("L1") + theme_classic() + scale_fill_manual(values = c("#00AFBB", "#FFA500", "#FF1493")) + ylim(c(0,0.028))
ggsave("../plots/L1_vitres_retrain.svg", height = 3, width = 6)
p
```

```{r}
library(dplyr)

temp = subset(dfall, dfall$Loss_type == 'L2')
# Data
data <- temp %>% select(Loss, Model) 
# Calculates mean, sd, se and IC
my_sum <- data %>%
  group_by(Model) %>%
  dplyr::summarise( 
    n=n(),
    mean=mean(Loss),
    sd=sd(Loss)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
# Standard deviation
p = ggplot(my_sum) +
  geom_bar( aes(x=Model, y=mean, fill=Model), stat="identity", alpha=0.7, width = 0.4) +
  geom_errorbar( aes(x=Model, ymin=mean-sd, ymax=mean+sd), width=0.08, colour="black", alpha=0.9, size=0.2) +
  geom_point(data = temp, aes(x = Model, y = Loss), color = 'black', 
              width = 0, alpha = 0.6, size = 0.75) +
  ggtitle("L2") + theme_classic() + scale_fill_manual(values = c("#00AFBB", "#FFA500", "#FF1493")) + ylim(c(0,0.00475))
ggsave("../plots/L2_vitres_retrain.svg", height = 3, width = 6)
p
```

```{r}
library(dplyr)

temp = subset(dfall, dfall$Loss_type == 'CE')
# Data
data <- temp %>% select(Loss, Model) 
# Calculates mean, sd, se and IC
my_sum <- data %>%
  group_by(Model) %>%
  dplyr::summarise( 
    n=n(),
    mean=mean(Loss),
    sd=sd(Loss)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
# Standard deviation
p = ggplot(my_sum) +
  geom_bar( aes(x=Model, y=mean, fill=Model), stat="identity", alpha=0.7, width = 0.4) +
  geom_errorbar( aes(x=Model, ymin=mean-sd, ymax=mean+sd), width=0.08, colour="black", alpha=0.9, size=0.2) +
  geom_point(data = temp, aes(x = Model, y = Loss), color = 'black', 
              width = 0, alpha = 0.6, size = 0.75) +
  ggtitle("CE") + theme_classic() + scale_fill_manual(values = c("#00AFBB", "#FFA500", "#FF1493"))
ggsave("../plots/CE_vitres_retrain.svg", height = 3, width = 6)
p
```
