
First test metrics changes


```{r}
library(ggplot2)
library(paletteer)
library(dplyr)

metrics = read.csv("../../reschange/xton/data/CH_result_xton.csv")
metrics2 = read.csv('../data/CH_result_xton_tacco.csv')
metricsall = rbind(metrics, metrics2)

## base line
averages <- metricsall %>%
  filter(!variable %in% c("ch_tacco", 'ch_snap')) %>%  
  group_by(X,k) %>% 
  summarise(value = mean(value, na.rm = TRUE))
averages$variable = 'ch_all_avg'
## self
metricslen = subset(metricsall, metricsall$variable %in%
                      c("ch_tacco", 'ch_snap'))
## combine
plotdf = rbind(metricslen, averages)

colors <- c("grey", "#3CB44B", "#FFE119", "#4363D8", "#F58231")

p = ggplot(plotdf,aes(x=k,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("CH") + scale_color_manual(values = 
colors) + scale_fill_manual(values = colors)
ggsave("../plots/ch_xton_tacco.svg", height = 3, width = 5)
p
```

```{r}
metrics = read.csv("../../reschange/xton/data/SS_result_xton.csv")
metrics2 = read.csv('../data/SS_result_xton_tacco.csv')
metricsall = rbind(metrics, metrics2)

## base line
averages <- metricsall %>%
  filter(!variable %in% c("ch_tacco", 'ch_snap')) %>%  
  group_by(X,k) %>% 
  summarise(value = mean(value, na.rm = TRUE))
averages$variable = 'ch_all_avg'
## self
metricslen = subset(metricsall, metricsall$variable %in%
                      c("ch_tacco", 'ch_snap'))
## combine
plotdf = rbind(metricslen, averages)

colors <- c("grey", "#3CB44B", "#FFE119", "#4363D8", "#F58231")

p = ggplot(plotdf,aes(x=k,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("SS") + scale_color_manual(values = 
colors) + scale_fill_manual(values = colors)
ggsave("../plots/ss_xton_tacco.svg", height = 3, width = 5)
p
```

```{r}
metrics = read.csv("../../reschange/xton/data/DB_result_xton.csv")
metrics2 = read.csv('../data/DB_result_xton_tacco.csv')
metricsall = rbind(metrics, metrics2)

## base line
averages <- metricsall %>%
  filter(!variable %in% c("ch_tacco", 'ch_snap')) %>%  
  group_by(X,k) %>% 
  summarise(value = mean(value, na.rm = TRUE))
averages$variable = 'ch_all_avg'
## self
metricslen = subset(metricsall, metricsall$variable %in%
                      c("ch_tacco", 'ch_snap'))
## combine
plotdf = rbind(metricslen, averages)

colors <- c("grey", "#3CB44B", "#FFE119", "#4363D8", "#F58231")

p = ggplot(plotdf,aes(x=k,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("DB") + scale_color_manual(values = 
colors) + scale_fill_manual(values = colors)
ggsave("../plots/db_xton_tacco.svg", height = 3, width = 5)
p
```

```{r}
metrics = read.csv("../../reschange/xton/data/Mod_result_xton.csv")
metrics2 = read.csv('../data/Mod_result_xton_tacco.csv')
metricsall = rbind(metrics, metrics2)

## base line
averages <- metricsall %>%
  filter(!variable %in% c("ch_tacco", 'ch_snap')) %>%  
  group_by(X,res) %>% 
  summarise(value = mean(value, na.rm = TRUE))
averages$variable = 'ch_all_avg'
## self
metricslen = subset(metricsall, metricsall$variable %in%
                      c("ch_tacco", 'ch_snap'))
## combine
plotdf = rbind(metricslen, averages)

colors <- c("grey", "#3CB44B", "#FFE119", "#4363D8", "#F58231")

p = ggplot(plotdf,aes(x=res,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("Mod") + scale_color_manual(values = 
colors) + scale_fill_manual(values = colors)
ggsave("../plots/mod_xton_tacco.svg", height = 3, width = 5)
p
```


#### now lets do umap

```{r}
ssnap = read.csv('../data/Xton_tacco_double_snap_combo_stable.csv')
ssnap$X = NULL # first row is rnum
colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap), assay="cnp")
snp <- ScaleData(snp) 
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:30)

# umap plotting
snp <- RunUMAP(snp, dims = 1:30)

df_meta = read.csv('../data/Xton_sub_meta_snap_feat_clusters_tacco.csv')
snp@meta.data$snap_label = df_meta$snapres1_ann

library(Polychrome)
set.seed(42)
P20 = createPalette(20,  c("#010101", "#ff0000"), M=1000)
P20_re = P20[sample(length(P20), length(P20))]
#swatch(P20_re)

#df_meta = read.csv('../data/save_spleen_ann_dec27.csv')
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$tacco_res1))

names(P20_re) = c('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
                '12', '13', '14', '15', '16', '17', '18', '19')

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 2,stroke = 0), cex = 0.5) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = P20_re)
ggsave("../plots/umap_xton_tacco.png",p1,height = 6, width = 7.8)
p1
```


##### b cells umap

```{r}
### res 1 version
df_meta$snap_ann_b = as.character(df_meta$tacco_res1ann)
df_meta$snap_ann_b[df_meta$tacco_res1 %in% c(0,3,6,12,16)] = 'B'
df_meta$snap_ann_b[df_meta$tacco_res1 %in% c(7)] = 'GC B'
df_meta$snap_ann_b[df_meta$tacco_res1 %in% c(11)] = 'replicating non-GC B'

###
ssnapb = subset(ssnap, df_meta$snap_ann_b %in% c('B', 'GC B','replicating non-GC B'))
df_metab = subset(df_meta, df_meta$snap_ann_b %in% c('B', 'GC B','replicating non-GC B'))

library(Seurat)
snpb <- CreateSeuratObject(counts = t(ssnapb), assay = "cnp")
SetAssayData(object = snpb, slot = "data", new.data =t(ssnapb), assay="cnp")
snpb <- ScaleData(snpb) 
snpb<- RunPCA(snpb, features = rownames(snpb))
snpb <-  FindNeighbors(snpb, dims = 1:30)
# umap plotting
snpb <- RunUMAP(snpb, dims = 1:30)

###
embdb = data.frame(umap1 = snpb@reductions$umap@cell.embeddings[,1],
                  umap2 = snpb@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_metab$snap_ann_b))

library(ggplot2)
p1 = ggplot(embdb)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 2,stroke = 0), cex = 0.6) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = c("B" = "#A8E890",
                                "GC B" = "#BFACE2",
                                "replicating non-GC B" = "#FC2947")) 
ggsave("../plots/umap_xton_tacco_bsub.png",p1,height = 6, width = 6.5)
p1
```

```{r}
### 
embdb = data.frame(umap1 = snpb@reductions$umap@cell.embeddings[,1],
                  umap2 = snpb@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_metab$tacco_res1))

library(ggplot2)
p1 = ggplot(embdb)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 2,stroke = 0), cex = 0.6) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = P20_re) 
ggsave("../plots/umap_xton_snap_bsub_tacco.png",p1,height = 6, width = 6.5)
p1
```


```{r}
plotdf = read.csv('../data/Xton_sub_meta_snap_feat_clusters_tacco.csv')

group.colors <- c( "clust" = "#FF1E00", "None" = "#FFFFFF00")
snap_b = c(7,11)
i = 0
for(clust in snap_b){ # do this by cluster number
  i = i + 1
  print(clust)
  temp = plotdf
  temp$plot = "None"
  temp$plot[temp$tacco_res1 == clust] = "clust"
  
  p = ggplot(temp, aes(x = x_centroid, y = y_centroid, color = plot)) +
    geom_point(size = 0.15, stroke = 0.15) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
    scale_color_manual(values=group.colors)
  
  assign(paste0("p", i), p)
}

library(patchwork)
pp = wrap_plots(p1,p2, ncol = 2)
pp
ggsave("../plots/spagcn_gcetc_b.png", height = 3, width = 6)
```





##### below not used







```{r}
#df_norm = read.csv('../../gd_xton/data/Xton_sub_norm.csv')
gene_name = read.csv('../../gd_xton/data/gene_names.csv')
colnames(df_norm) = gene_name$X0
df_norm_b = subset(df_norm, df_meta$snap_ann_b %in% c('B', 'GC B'))
rownames(df_norm_b) = paste0('cell_', rep(1:nrow(df_norm_b)))

snpb2 <- CreateSeuratObject(counts = t(df_norm_b), assay = "cnp")
SetAssayData(object = snpb2, slot = "data", new.data =t(df_norm_b), assay="cnp")

cus_umap = snpb@reductions$umap@cell.embeddings
rownames(cus_umap) <- colnames(snpb2)
custom_umap_dimreduc <- CreateDimReducObject(
  embeddings = as.matrix(cus_umap),
  key = "UMAP_",
  assay = DefaultAssay(snpb2)
)

snpb2[["custom_umap"]] <- custom_umap_dimreduc

FeaturePlot(object = snpb2, features = c('MKI67'), reduction = 'custom_umap')
```

```{r}
df_meta2 = read.csv('../data/Xton_sub_meta_snap_feat_clusters_taccoRes1.2.csv')
df_metab2 = subset(df_meta2, df_meta$snap_ann_b %in% c('B', 'GC B'))

### 
embdb = data.frame(umap1 = snpb@reductions$umap@cell.embeddings[,1],
                  umap2 = snpb@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_metab2$tacco_res1))

library(ggplot2)
p1 = ggplot(embdb)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 2,stroke = 0), cex = 0.6) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = P20_re) 
ggsave("../plots/umap_xton_snap_bsub_taccores15.png",p1,height = 6, width = 6.5)
p1
```



#### ok now I load stuff and draw b cells


```{r}
plotdf = read.csv('../data/Xton_sub_meta_snap_feat_clusters_res020304.csv')

group.colors <- c( "clust" = "#FF1E00", "None" = "#FFFFFF00")
snap_b = c(0,2,7,8)
i = 0
for(clust in snap_b){ # do this by cluster number
  i = i + 1
  print(clust)
  temp = plotdf
  temp$plot = "None"
  temp$plot[temp$snap_res02 == clust] = "clust"
  
  p = ggplot(temp, aes(x = x_centroid, y = y_centroid, color = plot)) +
    geom_point(size = 0.15, stroke = 0.15) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
    scale_color_manual(values=group.colors)
  
  assign(paste0("p", i), p)
}

library(patchwork)
pp = wrap_plots(p1,p2,p3,p4, ncol = 4)
pp
ggsave("../plots/res02_b.png", height = 3, width = 9)
```

