---
title: "feat_25clusterVer"
output: html_document
---

### save out

```{r}
library(Polychrome)
set.seed(42)
P25 = createPalette(25,  c("#010101", "#ff0000"), M=1000)
P25_re = P25[sample(length(P25), length(P25))]
swatch(P25_re)
```


```{r}
df_meta = read.csv('../data/spleen_feat25ver.csv')
feat = read.csv('../../../data/arturito_local/final_R_part/spleen/data/save_spleen_ann_0327.csv')
feat = feat[,c(5:35)]
rownames(feat) = paste0('cell_', rep(1:nrow(feat)))

library(Seurat)
featt <- CreateSeuratObject(counts = t(feat), assay = "cnp")
SetAssayData(object = featt, slot = "data", new.data =t(feat), assay="cnp")
featt <- ScaleData(featt) 
featt<- RunPCA(featt, features = rownames(featt))
featt <-  FindNeighbors(featt, dims = 1:30)

# umap plotting
featt <- RunUMAP(featt, dims = 1:30)
```

```{r}
### make feat25 version
bkc = P25_re
names(bkc) = c('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
               '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
               '23', '24')

embd = data.frame(umap1 = featt@reductions$umap@cell.embeddings[,1],
                  umap2 = featt@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$feat20))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = bkc)
ggsave("../plots/umap_spleen_feat25_1104.png",p1,height = 6, width = 7.8)
p1
```

```{r}
###
featb = subset(feat, df_meta$feat20_ann == 'B')
df_metab = subset(df_meta, df_meta$feat20_ann == 'B')

library(Seurat)
feattb <- CreateSeuratObject(counts = t(featb), assay = "cnp")
SetAssayData(object = feattb, slot = "data", new.data =t(featb), assay="cnp")
feattb <- ScaleData(feattb) 
feattb<- RunPCA(feattb, features = rownames(feattb))
feattb <-  FindNeighbors(feattb, dims = 1:30)
# umap plotting
feattb <- RunUMAP(feattb, dims = 1:30)
```

### save out

```{r}
embdb = data.frame(umap1 = feattb@reductions$umap@cell.embeddings[,1],
                  umap2 = feattb@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_metab$feat20))

library(ggplot2)
p1 = ggplot(embdb)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = bkc)
ggsave("../plots/umap_spleen_feat25_bcells_1104.png",p1,height = 6, width = 6.5)
p1
```



#################### now produce b cell locations


Start looking at subset of cells and there spatial locations

```{r}
df = df_meta # df with all the meta labels

plotdf = data.frame(f_clust = df$feat20,
                    f_ann = df$feat20_ann,
                    x = df$centroid_x,
                    y = df$centroid_y
                    )
```


```{r}
group.colors <- c( "clust" = "#FF1E00", "None" = "#FFFFFF00")
snap_b = c(2,3,5,6,9,12,18,19,21)
i = 0
for(clust in snap_b){ # do this by cluster number
  i = i + 1
  print(clust)
  temp = plotdf
  temp$plot = "None"
  temp$plot[temp$f_clust == clust] = "clust"
  
  p = ggplot(temp, aes(x = x, y = y, color = plot)) +
    geom_point(size = 0.2, stroke = 0.2) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
    scale_color_manual(values=group.colors)
  
  assign(paste0("p", i), p)
}

library(patchwork)
pp = wrap_plots(p1,p2,p3,p4,p5,p6,p7,p8,p9, ncol = 9)
pp
ggsave("../plots/feat25_b_1104.png", height = 3, width = 27)
```

