
########## now do ranking

```{r}

## spleen
resdf = read.csv('../data/spleen_metric_rank.csv')
ranked_data <- resdf %>%
  mutate(variable = recode(variable, "ch_spagcn" = "SpaGCN", "ch_sedr" = "SEDR",
                          "ch_snap" = "CellLENS", "ch_mofa" = "MOFA+", "ch_cca" = "CCA",
                          "ch_spice" = "SpiceMix", "ch_banksy" = "BANKSY",
                          "ch_feature" = "Feature", "ch_stlearn" = "stLearn",
                          "ch_concact" = "Concact", "ch_cellc" = "CellCharter",
                          "ch_muse" = "MUSE")) %>%
  mutate(type = factor(type, levels = c("Mod", "SS", "CH", "DB")))

d1 = ranked_data
d1$data = 'spleen'

## xt
resdf = read.csv('../data/xt_metric_rank.csv')
ranked_data <- resdf %>%
  mutate(variable = recode(variable, "ch_spagcn" = "SpaGCN", "ch_sedr" = "SEDR",
                          "ch_snap" = "CellLENS", "ch_mofa" = "MOFA+", "ch_cca" = "CCA",
                          "ch_spice" = "SpiceMix", "ch_banksy" = "BANKSY",
                          "ch_feature" = "Feature", "ch_stlearn" = "stLearn",
                          "ch_concact" = "Concact", "ch_cellc" = "CellCharter",
                          "ch_muse" = "MUSE")) %>%
  mutate(type = factor(type, levels = c("Mod", "SS", "CH", "DB")))

d2 = ranked_data
d2$data = 'xt'

## ton
resdf = read.csv('../data/ton_metric_rank.csv')
ranked_data <- resdf %>%
  mutate(variable = recode(variable, "ch_spagcn" = "SpaGCN", "ch_sedr" = "SEDR",
                          "ch_snap" = "CellLENS", "ch_mofa" = "MOFA+", "ch_cca" = "CCA",
                          "ch_spice" = "SpiceMix", "ch_banksy" = "BANKSY",
                          "ch_feature" = "Feature", "ch_stlearn" = "stLearn",
                          "ch_concact" = "Concact", "ch_cellc" = "CellCharter",
                          "ch_muse" = "MUSE")) %>%
  mutate(type = factor(type, levels = c("Mod", "SS", "CH", "DB")))

d3 = ranked_data
d3$data = 'ton'

## chl
resdf = read.csv('../data/chl_metric_rank.csv')
ranked_data <- resdf %>%
  mutate(variable = recode(variable, "ch_spagcn" = "SpaGCN", "ch_sedr" = "SEDR",
                          "ch_snap" = "CellLENS", "ch_mofa" = "MOFA+", "ch_cca" = "CCA",
                          "ch_spice" = "SpiceMix", "ch_banksy" = "BANKSY",
                          "ch_feature" = "Feature", "ch_stlearn" = "stLearn",
                          "ch_concact" = "Concact", "ch_cellc" = "CellCharter",
                          "ch_muse" = "MUSE")) %>%
  mutate(type = factor(type, levels = c("Mod", "SS", "CH", "DB")))

d4 = ranked_data
d4$data = 'chl'

## liv
resdf = read.csv('../data/liv_metric_rank.csv')
ranked_data <- resdf %>%
  mutate(variable = recode(variable, "ch_spagcn" = "SpaGCN", "ch_sedr" = "SEDR",
                          "ch_snap" = "CellLENS", "ch_mofa" = "MOFA+", "ch_cca" = "CCA",
                          "ch_spice" = "SpiceMix", "ch_banksy" = "BANKSY",
                          "ch_feature" = "Feature", "ch_stlearn" = "stLearn",
                          "ch_concact" = "Concact", "ch_cellc" = "CellCharter",
                          "ch_muse" = "MUSE")) %>%
  mutate(type = factor(type, levels = c("Mod", "SS", "CH", "DB")))

d5 = ranked_data
d5$data = 'liv'

## dfall

dfall = do.call(rbind, list(d1,d2,d3,d4,d5))
```


```{r}
df_summary <- dfall %>%
  group_by(variable, type) %>%
  summarize(avg_rank = mean(average_rank, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(variable) %>%
  mutate(total_rank = mean(avg_rank, na.rm = TRUE))
```

```{r}
# Step 2: Plot with reordered variable within each type
p = ggplot(df_summary, aes(x = reorder(variable, total_rank), y = avg_rank, fill = type)) +
  geom_bar(stat = "identity", color = "black", position = position_dodge(width = 0.8)) +
  geom_text(aes(label = round(avg_rank, 2)), vjust = -0.5, size = 3.5, position = position_dodge(width = 0.8)) +
  labs(title = "Average Rank of Methods by Type", x = "Method", y = "Average Rank (Lower is Better)") +
  facet_wrap(~ type, scales = "free_x") +  # Creates separate panels for each 'type'
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_brewer(palette = "Set3")  # Color palette for distinct groups
ggsave('../plots/rank_all.svg',p, height = 6, width = 12)
p
```



########## line plots below


```{r}
library(ggplot2)
library(paletteer)

metrics = read.csv("../data/XT/CH_result_xton.csv") # metrics prev calced
metrics2 = read.csv('../data/XT/CH_result_XT_rev.csv')
metricsall = rbind(metrics, metrics2)
#colorv = c("#f6511d","#ffb400","#00a6ed","#7fb800","#A149FA")
#names(colorv) = c('ch_snap', 'ch_feature', 'ch_concact', 'ch_muse', 'ch_spice')
# CH

p = ggplot(metricsall,aes(x=k,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("XT CH") + scale_color_manual(values = 
paletteer_d("ggsci::schwifty_rickandmorty")) + scale_fill_manual(values = 
paletteer_d("ggsci::schwifty_rickandmorty"))

#+ scale_fill_manual(values = colorv) + scale_color_manual(values = colorv)
#ggsave("../plots/xton/spleen_ch.svg", height = 3, width = 5)
p
```


```{r}
library(ggplot2)

metrics = read.csv("../data/XT/SS_result_xton.csv") # metrics prev calced
metrics2 = read.csv('../data/XT/SS_result_XT_rev.csv')
metricsall = rbind(metrics, metrics2)

#colorv = c("#f6511d","#ffb400","#00a6ed","#7fb800","#A149FA")
#names(colorv) = c('ch_snap', 'ch_feature', 'ch_concact', 'ch_muse', 'ch_spice')
# CH

p = ggplot(metricsall,aes(x=k,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("XT SS") + scale_color_manual(values = paletteer_d("ggsci::schwifty_rickandmorty")) + scale_fill_manual(values = 
paletteer_d("ggsci::schwifty_rickandmorty"))

#ggsave("../plots/spleen_ch_0327.svg", height = 3, width = 5)
p
```



```{r}
library(ggplot2)

metrics = read.csv("../data/XT/DB_result_xton.csv") # metrics prev calced
metrics2 = read.csv('../data/XT/DB_result_XT_rev.csv')
metricsall = rbind(metrics, metrics2)
metricsall = subset(metricsall, metricsall$variable != 'ch_stlearn')
metricsall = subset(metricsall, metricsall$variable != 'ch_sedr')

#colorv = c("#f6511d","#ffb400","#00a6ed","#7fb800","#A149FA")
#names(colorv) = c('ch_snap', 'ch_feature', 'ch_concact', 'ch_muse', 'ch_spice')
# CH

p = ggplot(metricsall,aes(x=k,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("XT DB") + scale_color_manual(values = paletteer_d("ggsci::schwifty_rickandmorty")) + scale_fill_manual(values = 
paletteer_d("ggsci::schwifty_rickandmorty"))

#ggsave("../plots/spleen_ch_0327.svg", height = 3, width = 5)
p
```


```{r}
library(ggplot2)

metrics = read.csv("../data/XT/Mod_result_xton.csv") # metrics prev calced
metrics2 = read.csv('../data/XT/Mod_result_XT_rev.csv')
metricsall = rbind(metrics, metrics2)
metricsall = subset(metricsall, metricsall$variable != 'ch_muse')

#colorv = c("#f6511d","#ffb400","#00a6ed","#7fb800","#A149FA")
#names(colorv) = c('ch_snap', 'ch_feature', 'ch_concact', 'ch_muse', 'ch_spice')
# CH

p = ggplot(metricsall,aes(x=res,y=value, colour=variable,fill = variable)) +
  stat_summary(geom = "line", fun.y = mean, size = 0.6) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_normal, fun.args=list(conf.int=0.95), alpha = 0.3, colour = NA) +
  theme_classic()+ ggtitle("XT Mod") + scale_color_manual(values = paletteer_d("ggsci::schwifty_rickandmorty")) + scale_fill_manual(values = 
paletteer_d("ggsci::schwifty_rickandmorty"))

#ggsave("../plots/spleen_ch_0327.svg", height = 3, width = 5)
p
```


###################### umap quick check

```{r}
library(Seurat)

ssnap = read.csv('../data/spleen/double_snap_combo_stable_0327.csv')

set.seed(123)
rid = sample(1:nrow(ssnap), 10000, replace = FALSE)

ssnap$X = NULL # first row is rnum
colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap[rid,]), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap[rid,]), assay="cnp")
snp <- ScaleData(snp) 
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:30)

# umap plotting
snp <- RunUMAP(snp, dims = 1:30)

##
df_meta = read.csv('../data/spleen/features_and_metadata.csv')
df_meta = df_meta[rid,]
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$cluster.termV2))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = paletteer_d("colorBlindness::PairedColor12Steps"))
ggsave("../plots/snap_sub_umap.png",p1,height = 6, width = 7.8)
p1
```


```{r}
library(Seurat)

ssnap = read.csv('../data/spleen/conv_output_epoch_200.csv')
ssnap$X = NULL

set.seed(123)
rid = sample(1:nrow(ssnap), 10000, replace = FALSE)

colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap[rid,]), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap[rid,]), assay="cnp")
snp <- ScaleData(snp) 
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:25)

# umap plotting
snp <- RunUMAP(snp, dims = 1:25)

##
df_meta = read.csv('../data/spleen/features_and_metadata.csv')
df_meta = df_meta[rid,]
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$cluster.termV2))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = paletteer_d("colorBlindness::PairedColor12Steps"))
ggsave("../plots/spagcn_sub_umap.png",p1,height = 6, width = 7.8)
p1
```



```{r}
library(Seurat)

ssnap = read.csv('../data/spleen/spleen_stlearn_pca30v2.csv')
ssnap$X = NULL

set.seed(123)
rid = sample(1:nrow(ssnap), 10000, replace = FALSE)

ssnap$X = NULL # first row is rnum
colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap[rid,]), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap[rid,]), assay="cnp")
snp <- ScaleData(snp) 
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:25)

# umap plotting
snp <- RunUMAP(snp, dims = 1:25)

##
df_meta = read.csv('../data/spleen/features_and_metadata.csv')
df_meta = df_meta[rid,]
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$cluster.termV2))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = paletteer_d("colorBlindness::PairedColor12Steps"))
ggsave("../plots/stlearn_sub_umap.png",p1,height = 6, width = 7.8)
p1
```


```{r}
library(Seurat)

ssnap = read.csv('../data/spleen/spleen_sedr_32n.csv')
ssnap$X = NULL

set.seed(123)
rid = sample(1:nrow(ssnap), 10000, replace = FALSE)

ssnap$X = NULL # first row is rnum
colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap[rid,]), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap[rid,]), assay="cnp")
snp <- ScaleData(snp) 
#snp[["pca"]] <- CreateDimReducObject(embeddings = as.matrix(ssnap[rid,]),
#                                     key = "PC_", assay = DefaultAssay(snp))
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:30)

# umap plotting
snp <- RunUMAP(snp, dims = 1:30)

##
df_meta = read.csv('../data/spleen/features_and_metadata.csv')
df_meta = df_meta[rid,]
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$cluster.termV2))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = paletteer_d("colorBlindness::PairedColor12Steps"))
ggsave("../plots/sedr_sub_umap.png",p1,height = 6, width = 7.8)
p1
```



```{r}
library(Seurat)

ssnap = read.csv('../data/spleen/cellsnap_data_spleen_banksy_r1-all.csv')
ssnap = ssnap[]

set.seed(123)
rid = sample(1:nrow(ssnap), 10000, replace = FALSE)

ssnap <- ssnap %>% select('PC1':'PC20')
colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap[rid,]), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap[rid,]), assay="cnp")
snp <- ScaleData(snp) 
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:19)

# umap plotting
snp <- RunUMAP(snp, dims = 1:19)

##
df_meta = read.csv('../data/spleen/features_and_metadata.csv')
df_meta = df_meta[rid,]
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$cluster.termV2))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 3,stroke = 0), cex = 1) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = paletteer_d("colorBlindness::PairedColor12Steps"))
ggsave("../plots/banksy_sub_umap.png",p1,height = 6, width = 7.8)
p1
```












