---
title: "xenium_LN5k"
output: html_document
---

####################### UMAP plotting

####################

```{r}
ssnap = read.csv('../data/XLN5K_double_snap_combo_stable.csv')
ssnap$X = NULL # first row is rnum
colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(ssnap) = paste0('cell_', rep(1:nrow(ssnap)))

library(Seurat)
snp <- CreateSeuratObject(counts = t(ssnap), assay = "cnp")
SetAssayData(object = snp, slot = "data", new.data =t(ssnap), assay="cnp")
snp <- ScaleData(snp) 
snp<- RunPCA(snp, features = rownames(snp))
snp <-  FindNeighbors(snp, dims = 1:30)

# umap plotting
snp <- RunUMAP(snp, dims = 1:30)
#p1 <- DimPlot(snp, label = TRUE, repel = TRUE, label.size = 2.5) #+ NoLegend()
#p1
```

```{r}
df_meta = read.csv('../data/XLN5k_sub_meta_snap_feat_clusters.csv')
snp@meta.data$snap_label = df_meta$snapres1_ann
p1 <- DimPlot(snp, label = TRUE, repel = TRUE, label.size = 5,
              group.by = 'snap_label', raster = FALSE) + NoLegend()
#p1
```

```{r}
library(Polychrome)
set.seed(42)
P20 = createPalette(24,  c("#010101", "#ff0000"), M=1000)
P20_re = P20[sample(length(P20), length(P20))]
#swatch(P20_re)
```


### save out

```{r}
#df_meta = read.csv('../data/save_spleen_ann_dec27.csv')
embd = data.frame(umap1 = snp@reductions$umap@cell.embeddings[,1],
                  umap2 = snp@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$snapres1))

#bkc = c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#e3d3d3', '#000000')
#names(bkc) = c('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
#               '12', '13', '14', '15', '16', '17', '18', '19', '20', '21')
names(P20_re) = c('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
                '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23')

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 2,stroke = 0), cex = 0.5) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = P20_re)
ggsave("../plots/umap_xln5k_snap.png",p1,height = 6, width = 7.8)
p1
```



########## looks good, work on the feature only version

```{r}
feat = read.csv('../data/XLN5k_sub_pc.csv')
feat = feat[,c(1:30)] # only use first 30 pCs
#colnames(ssnap) = paste0('PC_', rep(1:ncol(ssnap)))
rownames(feat) = paste0('cell_', rep(1:nrow(feat)))

library(Seurat)
featt <- CreateSeuratObject(counts = t(feat), assay = "cnp")
SetAssayData(object = featt, slot = "data", new.data =t(feat), assay="cnp")
featt@reductions$pca = CreateDimReducObject(embedding = as.matrix(feat),assay = DefaultAssay(featt),key = "PC_")
# input is already pca so skip these steps
#featt <- ScaleData(featt) 
#featt<- RunPCA(featt, features = rownames(featt))
featt <-  FindNeighbors(featt, dims = 1:30)

# umap plotting
featt <- RunUMAP(featt, dims = 1:30)
#p1 <- DimPlot(snp, label = TRUE, repel = TRUE, label.size = 2.5) #+ NoLegend()
#p1
```


```{r}
#df_meta = read.csv('../data/save_tonsil_ann_dec28.csv')
featt@meta.data$feat_label = df_meta$featres1_ann
p1 <- DimPlot(featt, label = TRUE, repel = TRUE, label.size = 5,
              group.by = 'feat_label', raster = FALSE) + NoLegend()
#p1
```


```{r}
#df_meta = read.csv('../data/save_spleen_ann_dec27.csv')
embd = data.frame(umap1 = featt@reductions$umap@cell.embeddings[,1],
                  umap2 = featt@reductions$umap@cell.embeddings[,2],
                  label = as.character(df_meta$featres1))

library(ggplot2)
p1 = ggplot(embd)  + 
  geom_point(aes(x=umap1, y=umap2, color=label,size = 2,stroke = 0), cex = 0.5) +
  labs( x = "tsne 1", y = "tsne 2") + theme_classic() + ggtitle("sr") +
  scale_color_manual(values = P20_re)
ggsave("../plots/umap_xln5k_feat.png",p1,height = 6, width = 7.8)
p1
```



########## do heatmap seurat style

```{r}
df_norm = read.csv('../data/XLN5k_sub_norm.csv')
gene_names = read.csv('../data/gene_names.csv')
colnames(df_norm) = gene_names$X0
rownames(df_norm) = paste0('cell_', rep(1:nrow(df_norm)))
test <- CreateSeuratObject(counts = t(df_norm), assay = "cnp")
SetAssayData(object = test, slot = "data", new.data =t(df_norm), assay="cnp")
test <- ScaleData(test)
test@meta.data$snap = df_meta$snapres1
test@meta.data$feat = df_meta$featres1
```


```{r}
## test snap diff
Idents(test) = factor(test@meta.data$feat, levels = c(0,1,2,3,4,5,6,7,8,9,10,11))
deg.feat <- FindAllMarkers(test, only.pos = FALSE)

library(dplyr)

deg.feat %>%
    group_by(cluster) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

maxcells  <- 5 * min(table(Idents(test)))
subbb = subset(test, downsample = maxcells)
pp = DoHeatmap(subbb, features = top10$gene)
#ggsave('../plots/xton_feat.pdf', height = 13, width = 5)
ggsave('../plots/xln5k_feat.png', height = 14, width = 6)
```


```{r}
## test snap diff
Idents(test) = factor(test@meta.data$snap, levels = c(0,1,2,3,4,5,6,7,8,9,10,
                                                      11,12,13,14,15,16,17,18,
                                                      19,20,21,22,23))
deg.feat <- FindAllMarkers(test, only.pos = FALSE)
deg.feat %>%
    group_by(cluster) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

maxcells  <- 5 * min(table(Idents(test)))
subbb = subset(test, downsample = maxcells)
pp = DoHeatmap(subbb, features = top10$gene)
#ggsave('../plots/xton_feat.pdf', height = 13, width = 5)
ggsave('../plots/xln5k_snap.png', height = 14, width = 8)
```


########## make all cell type location


```{r}
library(ggplot2)

df_meta$snapres1_ann_general = df_meta$snapres1_ann
df_meta$snapres1_ann_general[df_meta$snapres1_ann == 'GCR-DC'] = 'DC'
df_meta$snapres1_ann_general[df_meta$snapres1_ann == 'GCR-Macrophage'] = 'Macrophage'
df_meta$snapres1_ann_general[df_meta$snapres1_ann == 'GCR-T'] = 'T'

ggc = c("#8DD3C7","#BEBADA", "#FB8072", "#A6CEE3",
                                "#1F78B4", "#B2DF8A", "#33A02C",
                                "#FB9A99", "grey57", "#FDBF6F",
                                "#FF7F00")
names(ggc) = c('B',
    'T',
    'GCR-B',
    'DC',
    'Fibro/Stromal',
    'Vessel',
    'Macrophage',
    'Other immune')

p = ggplot(df_meta, aes(x = x_centroid, y = y_centroid2,
                        color = snapres1_ann_general, size = 15)) +
    geom_point(size = 0.35, stroke = 0.35) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
      scale_color_manual(values = ggc) + 
    theme(
      plot.background = element_rect(fill = "black")
      )
ggsave("../plots/cell_loc_xln5k.png",p ,height = 5, width = 7)
p

```









```{r}
plot = df_meta
plot$label = 'Other'
plot$label[plot$snapres1 == 14] = 'target'

ggc = c("white", "#FF69B4")
names(ggc) = c('Other','target')

plot$alpha = 1
plot$alpha[plot$label == 'Other'] = 0

p = ggplot(plot, aes(x = x_centroid, y = y_centroid2, color = label)) +
    geom_point(aes(alpha = alpha),stroke = 0.5, size = 0.5) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
      scale_color_manual(values = ggc) + 
    theme(
      plot.background = element_rect(fill = "white")
      )
ggsave("../plots/cellTFH_loc_xln5k.png",p ,height = 5, width = 7)
p

```


```{r}
plot = df_meta
plot$label = 'Other'
plot$label[plot$snapres1 == 16] = 'target'

ggc = c("white", "#FFA500")
names(ggc) = c('Other','target')

plot$alpha = 1
plot$alpha[plot$label == 'Other'] = 0

p = ggplot(plot, aes(x = x_centroid, y = y_centroid2, color = label)) +
    geom_point(aes(alpha = alpha),stroke = 0.5, size = 0.5) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
      scale_color_manual(values = ggc) + 
    theme(
      plot.background = element_rect(fill = "white")
      )
ggsave("../plots/cellTBM_loc_xln5k.png",p ,height = 5, width = 7)
p

```





```{r}
plot = df_meta
plot$label = 'Other'
plot$label[plot$snapres1 == 20] = 'target'

ggc = c("white", "#008000")
names(ggc) = c('Other','target')

plot$alpha = 1
plot$alpha[plot$label == 'Other'] = 0

p = ggplot(plot, aes(x = x_centroid, y = y_centroid2, color = label)) +
    geom_point(aes(alpha = alpha),stroke = 0.5, size = 0.5) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
      scale_color_manual(values = ggc) + 
    theme(
      plot.background = element_rect(fill = "white")
      )
ggsave("../plots/cellFDC_loc_xln5k.png",p ,height = 5, width = 7)
p

```

```{r}
plotdf = data.frame(x = df_meta$x_centroid, y = df_meta$y_centroid2, 
                    clustn = df_meta$featres1)
group.colors <- c( "clust" = "#FF1E00", "None" = "#FFFFFF00")
clusters = c(0,1,4,6,9)
i = 0
listplot = list()
for(clust in clusters){ # do this by cluster number
  i = i + 1
  print(clust)
  temp = plotdf
  temp$plot = "None"
  temp$plot[temp$clustn == clust] = "clust"
  
  p = ggplot(temp, aes(x = x, y = y, color = plot)) +
    geom_point(size = 0.5, stroke = 0.5) + theme_classic() +
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank(),
      plot.margin = unit(c(0.0001,0.0001,0.0001,0.0001), "mm")) +
    scale_color_manual(values=group.colors)
  listplot[[i]] <- p
  assign(paste0("p", i), p)
}

library(patchwork)
pp = wrap_plots(listplot, ncol = 5)
#pp
ggsave("../plots/featall.png", pp, height = 5, width = 35)
#p
```


